
version: '3.5'

services:

  #database only yet
  postgres:
    image: postgres
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    #   interval: 5s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 5s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
       - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    logging:
      driver: "none"
    networks:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    volumes:
       - pgadmin:/var/lib/pgadmin

networks:
  postgres:

volumes:
  pgadmin:
  postgres: