# Generated by Django 4.1.7 on 2023-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.TextField(default='FAKE'),
        ),
    ]
