# Generated by Django 4.1.7 on 2023-03-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.TextField(null=True),
        ),
    ]
