# Generated by Django 4.1.7 on 2023-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_experience_alter_user_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.TextField(),
        ),
    ]
